Homework 6
VShutkina/ValentinaShutkina pull request #6
Opened 2019-12-09 19:54 UTC by VShutkina

Homework 6 - completed

2019-12-09 21:17 UTC, khda91 requested changes
Please resolve comments

2019-12-09 21:17 UTC, khda91 commented on src/test/java/hw6/ex2/Ex2CucumberHooks.java
> +public class Ex2CucumberHooks {
Code duplication

2019-12-09 21:17 UTC, khda91 commented on src/test/java/hw6/ex2/RunTests.java
> +public class RunTests extends AbstractTestNGCucumberTests {
code duplication

2019-12-09 21:17 UTC, khda91 commented on src/test/java/hw6/ex2/steps/SecondExerciseActionSteps.java
> +public class SecondExerciseActionSteps extends AbstractBaseSteps {
Steps could be combined with ex1

2019-12-09 21:17 UTC, khda91 commented on src/test/java/hw6/ex2/steps/SecondExerciseAssertionSteps.java
> +public class SecondExerciseAssertionSteps extends AbstractBaseSteps {
steps could be combined with the ex1

2019-12-09 21:17 UTC, khda91 commented on src/test/java/hw6/ex2/steps/SecondExerciseModalSteps.java
> +public class SecondExerciseModalSteps extends AbstractBaseSteps {
code duplication

2019-12-10 10:56 UTC, VShutkina commented on src/test/java/hw6/ex2/Ex2CucumberHooks.java
> +public class Ex2CucumberHooks {
fixed

2019-12-10 10:56 UTC, VShutkina commented on src/test/java/hw6/ex2/RunTests.java
> +public class RunTests extends AbstractTestNGCucumberTests {
fixed

2019-12-10 10:56 UTC, VShutkina commented on src/test/java/hw6/ex2/steps/SecondExerciseActionSteps.java
> +public class SecondExerciseActionSteps extends AbstractBaseSteps {
fixed

2019-12-10 10:56 UTC, VShutkina commented on src/test/java/hw6/ex2/steps/SecondExerciseAssertionSteps.java
> +public class SecondExerciseAssertionSteps extends AbstractBaseSteps {
fixed

2019-12-10 10:56 UTC, VShutkina commented on src/test/java/hw6/ex2/steps/SecondExerciseModalSteps.java
> +public class SecondExerciseModalSteps extends AbstractBaseSteps {
fixed

2019-12-11 08:35 UTC, khda91 approved these changes
Approved. Could be merged into master branch

2019-12-11 09:02 UTC, merged